maxFitnessLogFilePath: "D:\\pythonProject\\DeepSpeaker\\maxFitness.txt"
averageFitnessLogFilePath: "D:\\pythonProject\\DeepSpeaker\\averageFitness.txt"
attackDataSetPath: D:\pythonProject\DeepSpeaker\dataSet\originalDataSet\attackDataSet
attackEmbedSetPath: D:\pythonProject\DeepSpeaker\dataSet\speakerEmbed\attackEmbedSet
# 是否重新创建最相似50文件列表
recreateSimilarityFileList: FALSE
# 存储最相似的50个文件地址的路径
similarityFilePath: "D:\\pythonProject\\DeepSpeaker\\DE\\similarityList"
# 攻击成功后，候选点的存储路径
candidateSavePath: "D:\\pythonProject\\DeepSpeaker\\DE\\successful\\candidatePoint.pt"
# 初始种群大小
initPopulationSize: 140
# 最大迭代次数，超过这个次数还未攻击成功，则攻击失败
maxIteration: 500
# 变异率
mutateRate: 0.5
# 交叉率
crossRate: 0.5
# 缩放因子
scaleFactor: 0.5
# 音频切片长度
audioSliceLength: 100